_target_: navsim.agents.diffusiondrive2.transfuser_agent.TransfuserAgent
_convert_: 'all'

config:
  _target_: navsim.agents.diffusiondrive2.transfuser_config.TransfuserConfig
  _convert_: 'all'

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5

  latent: False

checkpoint_path: /mnt/jimmys/DiffusionDrive/navsim/exp/training_hidden_agent_w_gaze_40epoch/2025.08.09.11.24.43/lightning_logs/version_0/checkpoints/hidden_agent_27and10e.ckpt
lr: 6e-4
